### ISSUE TITLE
npm version is missing lib/ folder

### ISSUE THREAD

**Issue by mroderick** [buildo/gh-issue-mover#1]
I just took this lovely tool for a spin, but found that the version published to npm does not contain the `lib/` folder, and so doesn't work.

I was able to get it working locally after building it from a clone.

I think this will be relatively simple to fix with a `prepublish` script.

If there's traction for it, then I am happy to try creating a PR to fix it.

**Comment by sashahilton00** [comment]
Would definitely be helpful, just encountered the same issue :)

**Comment by gabro** [comment]
@mroderick @sashahilton00 can you try with version 1.0.2?

**Comment by sashahilton00** [comment]
Works for me.

**Comment by gabro** [comment]
Nice, thanks for trying it @sashahilton00!
I can marked this as closed by 816d04a31c7504db413a4e01ff925e346db53ea1.

Thanks for reporting.
